### ISSUE TITLE
Http headers

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [yarax/swagger-to-graphql#10]
@yarax Would it be possible to ignore HTTP headers when generating the GraphQL schema since they can be added via the network request.

**Comment by yarax** [comment]
If I understood your concern correctly, is it acceptable for your case just remove headers from swagger parameters?

**Comment by Ashraf-Ali-aa** [comment]
@yarax that is an option, but ideally, I would want to keep the swagger schema the same as production. Can you tell me what method I need to change in order to skip header arguments? 
Also I notice that the swagger method descriptions are not added to the GraphQL Scheme, I'll see if I can resolve this issue.

**Comment by yarax** [comment]
I think ignoring original swagger parameters is not a good idea, but cutting out odd characters is probably reasonable. And mapping would increase interface complexity.
So I added cutting and also description from swagger endpoints, please check this for your purposes.

**Comment by Ashraf-Ali-aa** [comment]
@yarax thanks, changes look good 👍 , but I got a few more suggestions could we also add `summary` field from swagger and use the `operationId` for the graphql method name.

**Comment by yarax** [comment]
`operationId` as a type name is a good idea
https://github.com/yarax/swagger-to-graphql/issues/11
About `summary` I'm not sure where it should be in GraphQL: field has only description field

**Comment by yarax** [comment]
`operationId` is done as a type name if exists in `1.0.4`
Thanks for the issue!
