### ISSUE TITLE
Schema empty

### ISSUE THREAD

**Issue by wortkotze** [yarax/swagger-to-graphql#100]
:( everything is starting fine but the schema seems to be empty and the gui is thorwing an error 

{
  "errors": [
    {
      "message": "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"Map«string,object»\" does not."
    }
  ]
}

![bildschirmfoto 2018-12-20 um 00 30 35](https://user-images.githubusercontent.com/1026043/50254496-80d42f80-03ee-11e9-9990-dd0c8c57bb7e.png)

**Comment by yarax** [comment]
Hi. This is an internal graphql.js error, pointing out that type name is wrong. I actually doubt that it would work with Swagger either
