### ISSUE TITLE
v1.4.4 of swagger-to-graphql bundles graphql v14.0.2, causing issues w/ npm

### ISSUE THREAD

**Issue by ateamlunchbox** [yarax/swagger-to-graphql#101]
Hi there.

I'm new to NodeJS, but I think the v1.4.4 package of swagger-to-graphql includes graphql v14.0.2 in node_modules, and that's causing conflicts with a project of mine.  I noticed v1.4.3 of swagger-to-graphql does not include a node_modules directory (so I pinned my package.json to that version).  Was the inclusion of node_modules/graphql in v1.4.4 intentional?  Just wondering.

Keep up the good work.

**Comment by yarax** [comment]
Hi! Yes, the library included graphql as a peer dependency previously, now its just a regular dependency. I'm still not sure which option is better for developers use cases. What kind of problem did you face with?

**Comment by ateamlunchbox** [comment]
I have a project that depends on graphql and swagger-to-graphql and I have to use npm as my package manager (for various corporate reasons) and the version of graphql v14.0.2 embedded in swagger-to-graphql v1.4.4 was causing a strange error.  

I just tried to reproduce it and was unable to do so.  Please disregard my issue, and I apologize for bringing it up.  

If I see it again, I will comment here and add more detailed error information.

Thanks again.
