### ISSUE TITLE
data type did not support multiple types. 

### ISSUE THREAD

**Issue by wh00527** [yarax/swagger-to-graphql#102]
something like this: 

"type": [
            "null",
            "string"
          ],
It will throw error.  ```Error: Cannot build primitive type "null,string"```

**Comment by yarax** [comment]
OpenAPI doesn't support multiple types (and swagger tooling of course too, since it requires non trivial type system) https://github.com/OAI/OpenAPI-Specification/issues/458. In your case you can utilize "required" property of the object.
