### ISSUE TITLE
Dependencies - graphql 14+

### ISSUE THREAD

**Issue by gimlidc** [yarax/swagger-to-graphql#104]
There is critical vulnerability in `npm i` command:

npm WARN express-graphql@0.6.12 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed.

Current version of graphql is something like graphql@14.0.2

**Comment by yarax** [comment]
Hi, thanks, could not see graphql vulnerabilities, but fixed those which are recommended by npm
