### ISSUE TITLE
OpenAPI3 migration. Paths section

### ISSUE THREAD

**Issue by yarax** [yarax/swagger-to-graphql#125]
Please see the migration roadmap https://github.com/yarax/swagger-to-graphql/wiki/OpenAPI3-migration
Among things that I noticed so far:

- [x] https://github.com/yarax/swagger-to-graphql/issues/65
- [ ] https://github.com/yarax/swagger-to-graphql/issues/66
- [x] https://github.com/yarax/swagger-to-graphql/issues/58
- [ ] https://github.com/yarax/swagger-to-graphql/issues/60
- [x] servers section

**Comment by 0xR** [comment]
The servers section is already supported in under test:
https://github.com/yarax/swagger-to-graphql/blob/d2c51e52df6be6adf78922e02e8af0c2900a38a4/src/swagger.js#L50-L81

**Comment by 0xR** [comment]
The basic support for openapi 3 and its path sections has been released in #143 
#66 and #60 are enhancements that can be picked up later.
