### ISSUE TITLE
OpenAPI3 migration. Components section

### ISSUE THREAD

**Issue by yarax** [yarax/swagger-to-graphql#126]
Please see the migration roadmap https://github.com/yarax/swagger-to-graphql/wiki/OpenAPI3-migration
Among things that I noticed so far:
- [ ]  New structure instead of definitions (components/schemas)
- [ ]  responses
- [ ]  parameters
- [ ] examples
- [ ] requestBodies
- [ ] headers
- [ ] links
- [ ] callbacks
- [ ] securitySchemas

So they should be separated GraphQL types, if they're present in the schema. And accordingly can be referred to from other places

**Comment by 0xR** [comment]
Implemented in #143
