### ISSUE TITLE
Feature Request: Support Federation

### ISSUE THREAD

**Issue by dwelch2344** [yarax/swagger-to-graphql#139]
Any ideas on what it'd take to support Federation? Just getting my legs under me with it, but would be super nice if it could do it

**Comment by 0xR** [comment]
Federation could be supported by something like [schema transforms](https://www.apollographql.com/docs/graphql-tools/schema-transforms/). I haven't tried it yet. I don't think it should be part of the swagger-to-graphql itself. An example could be added to the documentation.

For now I don't have time to investigate.

**Comment by codef0rmer** [comment]
@0xR I'm also wanting this implementation. But up until I was thinking that it's not possible (https://github.com/apollographql/apollo-server/pull/30130).

Can you atleast jot down your thoughts and approach to make it happen so that I can spend some time to code?

**Comment by codef0rmer** [comment]
@0xR I also noticed that the schema generated by this tool is an executable schema while Angular Server can not consume it.

**Comment by 0xR** [comment]
Good news, I created the schema transform that I mentioned above. It could do with more documentation, but there is a working example. The idea is that you create the schema with swagger-to-graphql and add annotations with graphql-transform-federation.

https://github.com/0xR/graphql-transform-federation

**Comment by dwelch2344** [comment]
This is awesome to hear. Excited to check it out. Thanks!

**Comment by codef0rmer** [comment]
but @0xR is it not on NPM?

**Comment by 0xR** [comment]
Yes it is: https://www.npmjs.com/package/graphql-transform-federation
