### ISSUE TITLE
Using multiple Swagger JSON

### ISSUE THREAD

**Issue by codef0rmer** [yarax/swagger-to-graphql#141]
What would be the strategy to consume 2 or more Swagger JSON and serving them on same/different port, since `graphQLSchema` function does not take an array of proxyUrls/SwaggerPaths.

Is it even possible?

I tried with two ports which works fine but not sure if it's the recommended way:

```const app = express();
graphQLSchema('./swagger1.json', proxyUrl, customHeaders).then(schema => {
  app.use('/graphql', graphqlHTTP(() => {
    return {
      schema,
      graphiql: true
    };
  }));  
}).catch(e => {
  console.log(e);
});

graphQLSchema('./swagger2.json', proxyUrl, customHeaders).then(schema => {
  app.use('/graphql2', graphqlHTTP(() => {
    return {
      schema,
      graphiql: true
    };
  }));
}).catch(e => {
  console.log(e);
});

app.listen(4000, 'localhost', () => {
  console.info('http://localhost:4000/graphql or http://localhost:4000/graphql2');
});
```

**Comment by yarax** [comment]
That would be challenging, since schemas can overlap.
I would probably recommend convert each of the schemas separately and then use the schema stitching GraphQL tool or Federation from Apollo

**Comment by codef0rmer** [comment]
I think the schema stitching is what I'm doing right now which can be used in Angular this way: https://www.apollographql.com/docs/angular/features/multiple-clients/

Can federation be used along with `swagger-to-graphql`? If yes, any example code?

**Comment by codef0rmer** [comment]
I am just curious whether this tool is to be used in order to generate Types for GraphQL from Swagger JSON (where you have to write resolvers by hand) or directly swallow the Swagger JSON with `express-graphql`?

**Comment by codef0rmer** [comment]
Also feeding the service to gateway throws `Error: Apollo Server requires either an existing schema or typeDefs`. Any idea why?

```const gateway = new ApolloGateway({
  serviceList: [
    { name: 'pet', url: 'http://localhost:4001' }
  ],
});
const server = new ApolloServer({
  gateway,
  
  // Currently, subscriptions are enabled by default with Apollo Server, however,
  // subscriptions are not compatible with the gateway.  We hope to resolve this
  // limitation in future versions of Apollo Server.  Please reach out to us on
  // https://spectrum.chat/apollo/apollo-server if this is critical to your adoption!
  subscriptions: false,
});

server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});```

**Comment by codef0rmer** [comment]
I managed to make it work since the documentation was not updated. However, I had to write custom resolvers and use generated Graphql schemas by this tool since Federation is not compatible with it. 

```const { ApolloServer } = require("apollo-server");
const { ApolloGateway } = require("@apollo/gateway");

const gateway = new ApolloGateway({
  serviceList: [
    { name: "pets", url: "http://localhost:5001/graphql" },
    { name: "automation", url: "http://localhost:5002/graphql" },
  ]
});

(async () => {
  const { schema, executor } = await gateway.load();

  const server = new ApolloServer({ schema, executor });

  server.listen({port: 5000}).then(({ url }) => {
    console.log(`🚀 Server ready at ${url}`);
  });
})();```
