### ISSUE TITLE
How to generate Authorization token for GraphQL?

### ISSUE THREAD

**Issue by scheung38** [yarax/swagger-to-graphql#145]
const customHeaders = {
    Authorization: 'Basic xxxxx'
};

where to obtain xxxx token from?

Also since I am getting from the petstore.yaml example:
{
getPetById(petId: "1") {
  }
}

Error: unable to verify the first certificate, so do I use the same authorization token from example or need to generate a new one? If so how to generate this?

**Comment by yarax** [comment]
It's about https://swagger.io/docs/specification/authentication/bearer-authentication/
