### ISSUE TITLE
Get requests fail with socket hang up

### ISSUE THREAD

**Issue by kirill-konshin** [yarax/swagger-to-graphql#147]
Since original requests are `POST` following code has to be added after https://github.com/yarax/swagger-to-graphql/blob/master/src/index.ts#L47:

```ts
const { method, body, baseUrl, path, query, headers, bodyType } = req;
if (method === 'get') delete headers['content-length']; // <--------------- addition
const res = await requestPromise({
```

**Comment by kirill-konshin** [comment]
Also can be resolved by adding this middleware before graphqlHTTP:

```js
    app.use(function(req, res, next) {

        delete req.headers['content-length'];
        delete req.headers['accept-encoding'];

        next();

    });

    app.use(
        '/graphql',
        graphqlHTTP(() => ({
            schema,
            graphiql: true,
        })),
    );
```

**Comment by 0xR** [comment]
Nice find, it is a known issue. It will be solved in the 3.0 release (#146). There we don't attempt to pass all request headers to the backend. You get control to pick what you proxy or not.

**Comment by kirill-konshin** [comment]
Cool! When do you plan to release it?

**Comment by 0xR** [comment]
When I get time to add some documentation

**Comment by kirill-konshin** [comment]
Sure sure ) any ETA? No pressure, just trying to figure out the timeline.

**Comment by yarax** [comment]
@kirill-konshin feel free to come up with a PR and we can make a fix for 2.X version

**Comment by 0xR** [comment]
I released v3, let me know what you think

**Comment by kirill-konshin** [comment]
I'll try it right now

**Comment by kirill-konshin** [comment]
So far I got the installation error:

```
graphql-proxy dis$ npm i
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/xxx/node_modules/swagger-to-graphql/bin/swagger2graphql
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/xxx/node_modules/swagger-to-graphql/bin/swagger2graphql'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by kirill-konshin** [comment]
https://github.com/yarax/swagger-to-graphql/pull/152
