### ISSUE TITLE
Why GraphQL server throws "permission denied" error for the IP white-listed REST api?

### ISSUE THREAD

**Issue by codef0rmer** [yarax/swagger-to-graphql#149]
If I use the `swagger-to-graphql@1.8.0` to run a GraphQL server as given below, an IP white-listed API works in  both Postman as well as GraphQL Playground.

```
// This is not IP white-listed demo but just for the illustration purpose
const { ApolloServer } = require("apollo-server");
const graphQLSchema = require('swagger-to-graphql');

graphQLSchema('./pets.swagger.json', 'http://petstore.swagger.io/v2', {
    Authorization: 'Basic YWRkOmJhc2ljQXV0aA=='
}).then(schema => {
  const server = new ApolloServer({
    schema: schema
  });
  server.listen({ port: 6001 }).then(({ url }) => {
    console.log(`🚀 Server ready at ${url}`);
  });
}).catch(e => {
  console.log(e);
});
```

However, as soon as the swagger-to-graphql version is updated to 1.9.0 and beyond, the GraphQL query fails with forbidden permission denied error. Any idea why?

**Comment by 0xR** [comment]
You could try the new v3 api, this gives control back to the user to add headers where needed.

I'm not sure what is causing the permisson error. Probaby there is an issue with the Authorization header not being passed.

**Comment by codef0rmer** [comment]
Awesome! Worked like a charm. 👍
