### ISSUE TITLE
path item parameters not supported by the swagger parser

### ISSUE THREAD

**Issue by alexpit** [yarax/swagger-to-graphql#15]
I'm seeing this error when using [Path Item Object parameters](http://swagger.io/specification/#path-item-object-32) in a swagger schema (attached below). It seems the [parser code](https://github.com/yarax/swagger-to-graphql/blob/master/lib/swagger.js#L47) assumes there cannot be any parameters under a path, but only methods (http verbs). The swagger spec allows `parameters` as fixed fields under `Path Item`:

> A list of parameters that are applicable for all the operations described under this path. These parameters can be overridden at the operation level, but cannot be removed there.

Is this a built-in assumption meant to simplify the parser ?

```
  1) api schema converting:
     TypeError: Cannot convert undefined or null to object
      at getSuccessResponse (lib/swagger.js:21:10)
      at Object.keys.forEach.method (lib/swagger.js:58:19)
      at Array.forEach (native)
      at Object.keys.forEach.path (lib/swagger.js:47:24)
      at Array.forEach (native)
      at getAllEndPoints (lib/swagger.js:45:29)
      at loadSchema.then.swaggerSchema (lib/index.js:9:23)
```
[api-spec.json](https://github.com/yarax/swagger-to-graphql/files/965087/api.json.txt)

**Comment by yarax** [comment]
Thanks, I'll consider the fix
