### ISSUE TITLE
ReferenceError: jsonSchemaType is not defined

### ISSUE THREAD

**Issue by kirill-konshin** [yarax/swagger-to-graphql#17]
```
ReferenceError: jsonSchemaType is not defined
    at getPrimitiveTypes (/xxx/node_modules/swagger-to-graphql/lib/type_map.js:110:53)
```

In file https://github.com/yarax/swagger-to-graphql/blob/master/lib/type_map.js#L110 `jsonSchemaType` should be `jsonSchema.type`.

When fixed I get another error: #18.

**Comment by yarax** [comment]
Thanks, fixed
