### ISSUE TITLE
Error: Cannot build primitive type "file" on a latest petstore spec

### ISSUE THREAD

**Issue by kirill-konshin** [yarax/swagger-to-graphql#18]
When #17 is fixed I get

```
Error: Cannot build primitive type "file"
    at getPrimitiveTypes (/xxx/node_modules/swagger-to-graphql/lib/type_map.js:110:11)
```

The spec that I used: http://petstore.swagger.io/v2/swagger.json, see the diff (left yours right theirs): https://www.diffchecker.com/kGF4tVFG

**Comment by yarax** [comment]
It's true, file types are not supported yet.
Moved to https://github.com/yarax/swagger-to-graphql/issues/19

**Comment by 4F2E4A2E** [comment]
The OpenAPI community is rather unclear about this. They have removed file support and are aiming to hyper media extensions on the v3.
Untill then i propose to internally map file into object, like this:
```ts
--- petstore.swagger.json
+++ petstore.swagger.json
@@ -408,7 +408,7 @@
             "in": "formData",
             "description": "file to upload",
             "required": false,
-            "type": "file"
+            "type": "object"
           }
         ],
         "responses": {
```

@yarax would a pr for this be welcomed?

**Comment by yarax** [comment]
For me it seems to be too implicitly for library users. 
The error at least guides to understanding that this is an issue in your API

**Comment by silesky** [comment]
can we at least update the example?
