### ISSUE TITLE
use fetch instead of request-promise

### ISSUE THREAD

**Issue by sibelius** [yarax/swagger-to-graphql#23]
`fetch` is the official api to do requests

we just need to make sure that it is polyfilled by the user

**Comment by yarax** [comment]
What's the benefits?

**Comment by sibelius** [comment]
> fetch is the official api to do requests

it will be shipped with node version as well in newer versions

**Comment by yarax** [comment]
I wouldn't hurry with that. Polyfill looks robust, but still not so much as request library

**Comment by 0xR** [comment]
This is now possible in v3. You can use any http client you want. There is a `fetch` example provided.
