### ISSUE TITLE
Accept yaml format

### ISSUE THREAD

**Issue by sibelius** [yarax/swagger-to-graphql#25]
this could help https://github.com/nodeca/js-yaml

**Comment by yarax** [comment]
Sorry, didn't get, what are you going to use yaml for?

**Comment by sibelius** [comment]
the new format of swagger is `yaml` I guess, so it would be nice to support both formats

**Comment by yarax** [comment]
Fair, marking it as a release feature

**Comment by yarax** [comment]
Just checked, `json-schema-ref-parser` takes both JSON and YAML
