### ISSUE TITLE
Can we get the schema in a separate file?

### ISSUE THREAD

**Issue by megharao** [yarax/swagger-to-graphql#26]
Can we save the generated schema into a separate file as they have done here https://github.com/alonp99/graphql-rest-wrapper?

**Comment by yarax** [comment]
Yes, sure. Actually wanted to do that at some point. I guess it will be added in the next refactored version

**Comment by megharao** [comment]
When are you planning to release the next refactored version?

**Comment by yarax** [comment]
Next week hopefully

**Comment by megharao** [comment]
Hey, Is this feature available now?

**Comment by yarax** [comment]
Yep, 1.1 is there. Docs are not ready yet, but the usage is:
```
npm i -g swagger-to-graphql
swagger-to-graphql --swagger=./test/fixtures/petstore.json > /path/to/file
```

**Comment by megharao** [comment]
Hi,
Thanks for providing additional feature of writing the schema into a file. I tried this, and I think it's generating IDL format of schema something like this:

# A greeting for the person provided
type greetUser {
  # default field
  empty: String
}

type Query {
  viewer: viewer
}

type viewer {
  # Simply returns the string 'Hello `<person>`', where `person` is given as a parameter.
  greetUser(person: String): greetUser
}

I was expecting more of something like the schema generated here: https://github.com/alonp99/graphql-rest-wrapper

**Comment by megharao** [comment]
Hi,
Thanks for providing additional feature of writing the schema into a file. I tried this, and I think it's generating IDL format of schema something like this:

# A greeting for the person provided
type greetUser {
  # default field
  empty: String
}

type Query {
  viewer: viewer
}

type viewer {
  # Simply returns the string 'Hello `<person>`', where `person` is given as a parameter.
  greetUser(person: String): greetUser
}

I was expecting more of something like the schema generated here: https://github.com/alonp99/graphql-rest-wrapper

**Comment by yarax** [comment]
You mean code generation?

**Comment by megharao** [comment]
Yeah.. The code should be in the es6 format of javascript

**Comment by yarax** [comment]
No, sorry. I know it's popular in Swagger community but I'm not agree with this approach. 
Code should be written by developer.
