### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by rattrayalex-stripe** [yarax/swagger-to-graphql#34]
Hi, 

I ran the following: `swagger-to-graphql --swagger=../../openapi/schema.yaml > ./types.graphql`
It ran for >5min, but at the end `types.graphql` was empty. No error messages (or other messages) were printed. 

It might be nice to print error messages. 

Thanks!

**Comment by yarax** [comment]
Hi! Thanks for the issue.
Can you reproduce the error not in binary mode? Probably related to https://github.com/yarax/swagger-to-graphql/issues/33

**Comment by rattrayalex-stripe** [comment]
I believe it is essentially the same as #33. However it would be nice to not have to fiddle with the source code to see error messages. I think really this is a request to use `--out-file=some/path` instead of `> some/path`.

**Comment by yarax** [comment]
Error messages now are appearing since 1.1.7 (api is the same)
But call stack size issue is not solved yet
