### ISSUE TITLE
Embedded $ref directives crash conversion

### ISSUE THREAD

**Issue by capouch** [yarax/swagger-to-graphql#39]
Double whammy for me: new to Swagger and graphQL both, so lots of room to learn things.

I have been able to successfully convert Swagger v2 files to graphQL, **except** when the Swagger source files contain $ref directives.

Is there a workaround?

[events.json.txt](https://github.com/yarax/swagger-to-graphql/files/1322556/events.json.txt)

[events.graphql.txt](https://github.com/yarax/swagger-to-graphql/files/1322557/events.graphql.txt)

**Comment by yarax** [comment]
So the error message in your events.graphql.txt file is actually correct: containers definition doesn't exist in events.json.txt
