### ISSUE TITLE
Error: Names must match

### ISSUE THREAD

**Issue by marticrespi** [yarax/swagger-to-graphql#40]
Hi,

I have tried to convert my rest to graphql but its shows me an error and I dont know why, my swagger schema working well and is well built I think. Can you help me? I have attached my swagger.json and my types results ( renamed to txt to can be uploaded).

[schema.txt](https://github.com/yarax/swagger-to-graphql/files/1394303/schema.txt)
[types.txt](https://github.com/yarax/swagger-to-graphql/files/1394304/types.txt)

Thanks!

**Comment by yarax** [comment]
Hi,

The thing is that in your schema it's pointed `operationId` with invalid for GraphQL `{` character:
```
 "/v{VERSION}/organizations/{ORGANIZATION_ID}/available_payment_methods" : {
            "post" : {
                "tags" : [
                    "Client"
                ],
                "operationId" : "V{VERSIONOrganizationsByORGANIZATION_IDAvailable_payment_methodsPost",
```

Swagger2graphql takes operationId if it exists and converts the path if not.
