### ISSUE TITLE
Support for basic auth

### ISSUE THREAD

**Issue by 4F2E4A2E** [yarax/swagger-to-graphql#42]
Hello there and thank you for this really helpfull lib!

Is there a way of setting the basic auth through the api?
Is it planed to support basic auth authorization?

1. Setting the header information through the api does not work: 
```js
[...]
graphQLSchema('./swagger.json').then(schema => {
    app.use('/graphql', graphqlHTTP((req) => {
        req.headers['Authorization'] = 'Basic: YWRkOmJhc2ljQXV0aA==';
        req.headers['X-Custom'] = 'custom-payload-xyz';
        return {
            schema,
[...]
```

2. Setting the header in the resolver function does work: 
https://github.com/yarax/swagger-to-graphql/blob/master/lib/index.js#L80
```js
[...]
var resolver = function resolver(endpoint) {
  return function () {
    var _ref = (0, _asyncToGenerator3.default)(_regenerator2.default.mark(function _callee(_, args, opts) {
      var req, res;
      return _regenerator2.default.wrap(function _callee$(_context) {
        while (1) {
          switch (_context.prev = _context.next) {
            case 0:
              req = endpoint.request(args, opts.GQLProxyBaseUrl);

              req.headers['Authorization'] = 'Basic: YWRkOmJhc2ljQXV0aA==';
              if (opts.BearerToken) {
                req.headers.Authorization = opts.BearerToken;
              }
              _context.next = 4;
              return (0, _requestPromise2.default)(req);
[...]
```

**Comment by 4F2E4A2E** [comment]
With this PR, that's how custom headers and authentication can look like:
## Authorization

Basic Auth example:
```js
 ...
  context: {
    GQLProxyBaseUrl: API_BASE_URL,
    headers: {
      Authorization: 'Basic YWRkOmJhc2ljQXV0aA==',
      "X-Custom": 'customValue'
    }
    BearerToken: req.get('authorization')
  },
 ...
```

Bearer Token example:
```js
 ...
  context: {
    GQLProxyBaseUrl: API_BASE_URL,
    headers: {
      Authorization: req.get('authorization'),
      "X-Custom": 'customValue'
    }
  },
 ...
```

**Comment by yarax** [comment]
yes, now it supports BearerToken option, which is basically `Authorization` header. But probably it makes senses to proxy any set of headers. Thanks for the PR!

**Comment by yarax** [comment]
published as 1.2.1

**Comment by fizxmike** [comment]
Does this cover NTLM?

**Comment by 4F2E4A2E** [comment]
@fizxmike never tested on a MS-IIS, but i don't think it would work either. Still, maybe you could implement a layer between thos using https://www.npmjs.com/package/express-ntlm

What do you think?

**Comment by MrBoutte101** [comment]
the ability to pull a Bearer Token off the header of a request for an authenticated endpoint. Which is essentially no different than your typical GraphQL resolver that taps into `context.req.get('authorization')`

**Comment by MrBoutte101** [comment]
[here](https://github.com/yarax/swagger-to-graphql/commit/e4b33cb45ecd9269aec4886477ab5e68f1d18477#diff-04c6e90faac2675aa89e2176d2eec7d8L59) the Bearer Token example has been removed altogether
