### ISSUE TITLE
Passing in the endpoint URL

### ISSUE THREAD

**Issue by kbrandwijk** [yarax/swagger-to-graphql#49]
I am trying to integrate this library in a concept for graphql bindings. The issue I am facing is that the endpoint URL context variable name is hardcoded, so I can't use it with multiple bindings. Would it be possible to come up with an alternative way to specify the endpoint URL, preferable by passing it into the constructor, instead of having to specify it on the context?

This is really blocking me from integrating your library.

I would propose an optional parameter on the `build()` method, that gets passed in to `schemaFromEndpoints`. Preferably the endpoint itself, or a function if you want to specify it on the context, so:

`build('./swagger.json', ctx => ctx.myEndpoint)` or `build('./swagger,json', 'http://my.endpoint.com')`

**Comment by yarax** [comment]
Hi, @kbrandwijk 
Good point, I had such thoughts, because exactly, we need to pass url only once.
Another thing, that we could do within this PR is to retrieve url from swagger's `basePath` and then it's again available once after schema is parsed. And if any of options (in constructor or in context) is present, then it rewrites basePath.
What do you think?

**Comment by kbrandwijk** [comment]
I don't really follow the 'available once again after schema is parsed'. If you mean defaulting to swagger's `basePath` when no endpoint is passed in, that seems like a good idea.

I had to change a number of other things to allow proper integration (like not using the `viewer` field), which I did in my fork. I have used that for my binding integration here: https://github.com/graphql-binding/graphql-binding-openapi.

If you are interested in both allowing a configuration option for `viewer` and in passing in the endpoint like in my PR (with the added option to default to the one in the swagger config) then I can get rid of my fork, which would be great.

**Comment by yarax** [comment]
Omitting of `viewer` field is a quite hard implicit limitation for most of library users

**Comment by yarax** [comment]
Available in 1.2.3
Thanks for PR!

**Comment by 4F2E4A2E** [comment]
The readme should be extended with this new feature.
@viewer: IMHO not omitting and at the same time not offering a possibility to override it or at least deactivate it is hard as well.

**Comment by kbrandwijk** [comment]
Maybe that viewer part should get it's own issue?
