### ISSUE TITLE
Proposal: Remove the viewer node

### ISSUE THREAD

**Issue by 4F2E4A2E** [yarax/swagger-to-graphql#55]
@yarax  
What's the intent purpose of`viewer` and why is it there?
I rather would have this optional and propose to remove it. What do you say?

**Comment by 4F2E4A2E** [comment]
ping 🙈

**Comment by yarax** [comment]
Viewer is a standard practice of graphql applications, which helps with auth features https://medium.com/workflowgen/graphql-schema-design-the-viewer-field-aeabfacffe72
It can be called in any way, but I think it's worth it. It allows to scale your api at some point.

**Comment by 4F2E4A2E** [comment]
That makes totally sense, thank you. Should mutation not have the same layer then?

**Comment by yarax** [comment]
Mutations don't use it, but I just did a quick research, Relay modern doesn't need the viewer field anymore, and Sashko (https://stackoverflow.com/questions/39938560/graphql-viewer-for-mutations/39939747#39939747) and Lee (https://github.com/lucasbento/graphql-pokemon/issues/1#issue-184547046) suggest not to use Viewer anymore, keeping authorization on the level of resolver (as we do)
So I removed it, available in v1.2.6
Thanks for help again!
