### ISSUE TITLE
Getting error: Don't know how to handle schema ...

### ISSUE THREAD

**Issue by tforster** [yarax/swagger-to-graphql#56]
I'm doing a little late afternoon R&D to determine the viability of moving some or all of our ~50 endpoints API from REST to GraphQL. I came across swagger2GraphQL and thought it might be a great tool to help. I have converted my swagger.yaml to a swagger.json but when I run 

`swagger-to-graphql --swagger=./api/swagger/swagger.json` I receive 

Error: Don't know how to handle schema {"description":"The total amount to be submitted to Stripe including subTotal, rylliFee and stripeFee"} without type and schema

Followed by a stack dump. My swagger.json is 3125 lines and the swagger.yaml version is running our API nicely. Since this is just a quick R&D exercise during some downtime I can't invest too heavily. 

Any suggestion where I might start to debug this issue.

FWIW: Swagger version 2 and it does verify with `swagger project verify`.

**Comment by peterjaric** [comment]
I got this error too, and since there was no answer to this question I decided to try to debug it, and I actually found the problem. I had this in the swagger file:
```

"uri": {
          "description": "something something",
          "example": "https://example.com"
        },
```
And when I changed it to this, it worked:

```
"uri": {
          "description": "something something",
          "example": "https://example.com",
          "type": "string"
        },
```

**Comment by yarax** [comment]
This happens when schema (for example for parameter) doesn't have any information about its type. Since GraphQL strongly typed schema cannot be processed

**Comment by cyrus-za** [comment]
I am getting the same error but I do actually have the type in my schema.  In fact the error message even logs it in there.
```sh
Error: Don't know how to handle schema {"name":"account_invite_ids","in":"query","description":"Comma separated AccountInvite ids","schema":{"type":"string"}} without type and schema
```
This happens in `/node_modules/swagger-to-graphql/lib/typeMap.js:107:15`

```json
 	"express": "^4.17.1",
    "express-graphql": "^0.8.0",
    "graphql": "^14.3.1",
    "graphql-playground-middleware-express": "^1.7.12",
    "swagger-to-graphql": "^1.8.0"
```
Node 11.14.0
Yarn 1.16
MacOS Mojave 10.14.5

**Comment by cyrus-za** [comment]
EDIT: found the issue in `swagger-to-graphql/lib/index.js`

![image](https://user-images.githubusercontent.com/1845861/59377924-c3ffd180-8d85-11e9-9280-32b47f2ebb5d.png)

As you can see the type property on schema is undefined by inside the `jsonSchema` subfield there's a schema on there with `type` set to `string`. 

I am assuming that it is due to swagger version or something being unsupported. I did not setup the actual API so will need to speak to the dev who did that for more info, but the json does have `openapi: "3.0.0",` at the top. 

Do we only support v2.0 here?
