### ISSUE TITLE
[Feature request] Support OpenAPI 3.0

### ISSUE THREAD

**Issue by ehmicky** [yarax/swagger-to-graphql#58]
Great project!

Is there any plan to support OpenAPI 3.0 in the future?

I've noted the following incompatibilities between OpenAPI 2.0 / Swagger and OpenAPI 3.0:
  - `response.schema` is not available in OpenAPI 3.0 anymore. Instead `response.contents.MIME.schema` is used.
  - parameters are quite different in OpenAPI 3.0
  - `consumes` and `produces` are not available anymore in OpenAPI 3.0. Instead `Content-Type` and `Accept` HTTP headers should be used. Also several properties now specify the MIME type.
  - although the rest follows OpenAPI 2.0, this project already follows OpenAPI 3.0 when it comes to the `servers` property. However OpenAPI 3.0 also allow path definitions to override the `servers` property.
  - OpenAPI 3.0 renames the `definitions` property to `schemas`

**Comment by yarax** [comment]
Very nice proposals. That should be definitely be done

**Comment by yarax** [comment]
It's not TypeScript, it's js + flow, but any help is appreciated and we can help with types

**Comment by 0xR** [comment]
OpenAPI 3 support is implemented in #143 and released as 1.9. Let me know what you think!
