### ISSUE TITLE
[Feature request] Use `GraphQLFloat` instead of `GraphQLInt` for JSON schema type `number`

### ISSUE THREAD

**Issue by ehmicky** [yarax/swagger-to-graphql#63]
The JSON schema type `integer` seems to meet `GraphQLInt` while the JSON schema type `integer` seems to meet `GraphQLFloat` (at the moment it is `GraphQLInt`).

**Comment by yarax** [comment]
https://github.com/yarax/swagger-to-graphql/pull/71
