### ISSUE TITLE
[Feature request] Support `pathDefinition.parameters` OpenAPI property

### ISSUE THREAD

**Issue by ehmicky** [yarax/swagger-to-graphql#65]
Parameters can be defined at the path definition level with OpenAPI. The current implementation only look for parameters at the operation level.

Note that libraries like [`swagger-parser`](https://github.com/BigstickCarpet/swagger-parser) and [`sway`](https://github.com/apigee-127/sway) might help normalize those types of properties. They can also validate the specification.

**Comment by 0xR** [comment]
This was fixed #120 which is released in 1.5
