### ISSUE TITLE
Which npm package is the real one?

### ISSUE THREAD

**Issue by uLan08** [yarax/swagger-to-graphql#70]
I am going to assume that this is the [npm package](https://www.npmjs.com/package/swagger-to-graphql) this repo is referencing  but I saw [this](https://www.npmjs.com/package/@kbrandwijk/swagger-to-graphql) and npm says that it has more downloads but it just seems to be a fork of this repo and yet I can't seem to find the repo for the other one.

**Comment by 4F2E4A2E** [comment]
@kbrandwijk

**Comment by yarax** [comment]
@kbrandwijk if you guys are using the original `swagger-to-graphql` now, could you please change the description of your fork not to confuse users.

**Comment by TimSusa** [comment]
For me, I ran into the same confusion.

**Comment by yarax** [comment]
@kbrandwijk ping

**Comment by yarax** [comment]
@kbrandwijk friendly reminder

**Comment by 0xR** [comment]
The fork was created when it was not possible to override the host. This is now possible and this package is the official one.

The code of the fork is available here: https://github.com/graphql-binding/swagger-to-graphql

I think this says enough: `This branch is 3 commits ahead, 128 commits behind yarax:master.`


For more details check out: https://github.com/graphql-binding/graphql-binding-openapi/issues/1

**Comment by yarax** [comment]
The point here is to change the README in both GitHub repo and NPM not to confuse users of using outdated library
