### ISSUE TITLE
Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by thejibz** [yarax/swagger-to-graphql#77]
Hello,

I found myself getting the error: **Cannot read property 'headers' of undefined** when trying to execute a graphQL request.

In order to fix it I had to add a check on the following line:
https://github.com/yarax/swagger-to-graphql/blob/8e5976ede8360d82a12ee10428dee714f894ebab/lib/index.js#L74

`if (opts !== undefined && opts.headers)`

Regards,
JB

**Comment by yarax** [comment]
it seems like you didn't add `express-graphql` middleware to your application, because the third argument to resolver from `express-graphql` is a request object

**Comment by thejibz** [comment]
Ha yes it could be the cause of my problem ! In fact, I dont want to expose an endpoint with express-graphql, I just want to use the GraphQL engine to performs the requests on my backend and then I manage myself how I use the result (e.g. sending the response with other means...)

Thank you.

**Comment by TimSusa** [comment]
What about closing this issue?
