### ISSUE TITLE
Error returning Data

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [yarax/swagger-to-graphql#8]
When I try to use the demo `pet store` example via GraphQL it fails to return any data even thou swagger API it returns the data 
http://petstore.swagger.io/#!/store/getOrderById
`curl -X GET --header 'Accept: application/json' 'http://petstore.swagger.io/v2/store/order/7'`
### GraphQl
```
{
  viewer {
    get_store_order_orderId(orderId: 7) {
      id
      petId
      shipDate
    }
  }
}
```

### return data
```
{
  "data": {
    "viewer": null
  }
}
```

**Comment by yarax** [comment]
Thanks for the issue! 

Seems like with new versions of libraries graphql requires to have a root resolver (for `viewer`) as well. Please try the new updated version.

Also note, that GraphQL does not support integers greater than 32 http://facebook.github.io/graphql/#sec-Int
At the same time swagger has `int64` format. So you should use strings instead:
```
{
  viewer {
    get_store_order_orderId(orderId: "7") {
      id
      petId
      shipDate
    }
  }
}
```

**Comment by Ashraf-Ali-aa** [comment]
@yarax thanks its working now 👍
