### ISSUE TITLE
[Question] DataLoader

### ISSUE THREAD

**Issue by zerocowl** [yarax/swagger-to-graphql#82]
Great job!!
I have a doubt about DataLoader, how could I add to resolvers? or is it not possible?

**Comment by 4F2E4A2E** [comment]
DataLoader?
The resolvers are dynamic at runtime, static resolvers have to be written manually, for that, generate your gql schema and from there you go further writing your own resolver functions:
```
node ./node_modules/swagger-to-graphql/bin/swagger2graphql  --swagger=./src/swagger.json > ./src/swagger.graphqls
```
