### ISSUE TITLE
[BUG] Wrong description placement

### ISSUE THREAD

**Issue by Eddie-CooRo** [yarax/swagger-to-graphql#87]
in a *.graphql file when we have descriptions outside of types or inputs, the opening and closing """ should be on their own lines. 

Take a look at this example:
![capture](https://user-images.githubusercontent.com/20463083/42741624-3c83b92c-88c9-11e8-85c6-3ceb79d7abfe.PNG)

I've fixed the above one(at line 107) manually.

**Comment by fabien0102** [comment]
Just to add the specification link:
http://facebook.github.io/graphql/June2018/#sec-Descriptions

**Comment by yarax** [comment]
@fabien0102 is right, swagger2graphql has nothing to do with this
