### ISSUE TITLE
Update to GraphQl IDE

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [yarax/swagger-to-graphql#9]
I have found this project which is a really good GraphQL IDE, and it supports HTTP headers
https://github.com/redound/graphql-ide

**Comment by yarax** [comment]
`swagger-to-graphql` doesn't depend on any graphql IDEs, it's just types wrapper (swagger => graphql) + REST resolvers. You can use whatever you want IDE in your project with existing graphql schema.
