### ISSUE TITLE
Project questions

### ISSUE THREAD

**Issue by Inoir** [yarax/swagger-to-graphql#96]
- about 5 months no release
- peerDependency of graphQL is **0.13.0**, currently newest version of graphql is **14.0.2** 
- pull requests open without reply or merge
- issues open for like 2 years
- owner seem inactive

Please dont let the project die

**Comment by yarax** [comment]
Just become a contributor! (seriously)
Sorry, unfortunately I completely don't have time, but promise to at least review and merge open PRs and test the library with a newer version of graphql
btw @4F2E4A2E thank you a lot with your help
I also would like to make a big refactoring to make the structure of code and internal processes more clear. So if anyone have thoughts, you are more than welcome to propose a way to do it.

**Comment by 4F2E4A2E** [comment]
> Just become a contributor! (seriously)
He is right @Inoir , but did it work for you? Did you test it with a newer version of graphql? Are you going to test and give us feedback? It would be very welcomed :)

> btw @4F2E4A2E thank you a lot with your help
You're just too kind :)

**Comment by 0xR** [comment]
I helped out with some releases, more help is always welcome.
