### ISSUE TITLE
Are $ref's key to this project?

### ISSUE THREAD

**Issue by tbrannam** [yarax/swagger-to-graphql#97]
@yarax  While investigating https://github.com/APIDevTools/swagger-parser - I came across the option to `dereference` instead of `bundle`.  Dereference will actually dereference the `$ref` within the swagger `paths` which seems like it removes some complexity.   I started looking at using this as an opportunity to simply a few edge cases that I'm seeing with my Swagger yaml.  

I have concerns that I'm missing something fundamental to this project.

**Comment by tbrannam** [comment]
I think I found the weakness of this approach - if you have a nested object inside a param - you will loose the names which would be mapped to GraphQL types.

**Comment by yarax** [comment]
@tbrannam exactly, besides that we still have issues with dereferencing, e.g https://github.com/yarax/swagger-to-graphql/issues/86
