### ISSUE TITLE
Multi-version support?

### ISSUE THREAD

**Issue by tbrannam** [yarax/swagger-to-graphql#98]
@yarax There are a number of breaking changes between Swagger (2.0) and OpenAPI (3.0).  Supporting both would require a bit of refactoring.  Or would you support a major version change to document a breaking change?  This would require 2.0 users to update their spec or use a migration script before using this library.

**Comment by yarax** [comment]
It's still an open question, the change is quite big, currently we don't have resources to release the OpenAPI support (maybe you could help?). But anyway, that would be a changing of our major version, switching completely to OpenAPI, so should not break existing projects which use the library. If someone would still need Swagger 2.0, they still will be able yo use 1.* version of swagger2graphql
